### PR TITLE
Add more info from MechDB.

### PR DESCRIPTION
**Pull request by Bak3y**
This PR adds more info to the `SP.csv` file with data pulled from MechDB.  This includes tonnage, class, and faction info per chassis.

### CODE REVIEW

**Comment by Zach-G** [comment]
What is meant by bad responses from mechdb? What are the kinds of errors you are running into? With this information, I may be able to offer some help so that it works before merging the pull request.

**Comment by Bak3y** [comment]
> What is meant by bad responses from mechdb? What are the kinds of errors you are running into? With this information, I may be able to offer some help so that it works before merging the pull request.

No errors as long as MechDB responds, but the app isn't set up to handle errors well if they occur is what I'm saying.

**Comment by Zach-G** [comment]
Could place the for-loop you created into an if statement checking the status of mechdb. If apistatuscode != 200 or whatever,set those entries as 'NA' and print that mechdb failed to properly load the request for the specific 'Mech . Else, do the for-loop to gather the information from the API.

This would be a band-aid fix that would allow it to still run.

One thing to note is that mech_name created on line 269 is not the display name of the mech, it is the user re-name of the mech from within the Mech Lab.
image

The mech key of the dictionary we are are looping through (dict_mechIDs) is the proper display name.

Knowing this, does it help?

Edit: My logic was wrong, this has been fixed.

**Comment by Zach-G** [comment]
As for your question about whether it should be a separate csv from owned_mechs_SP. I plan on just renaming the file to be playername_owned_mechs.csv. The SP was meant to be a way to differentiate between the two owned_mechs csv files I was previously creating but I opted to using just the SP as it was more relevant.

**Comment by Bak3y** [comment]
@Zach-G - updated logic around response from MechDB - see if things look better now.

**Review by Zach-G — APPROVED** [review]
Approved. Thank you for adding the mechdb API code!

**Pull request merged**
